/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'ai-projects': AiProject;
    'prompt-templates': PromptTemplate;
    sites: Site;
    'blog-templates': BlogTemplate;
    'blog-posts': BlogPost;
    'site-links': SiteLink;
    'test-runs': TestRun;
    articles: Article;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'ai-projects': AiProjectsSelect<false> | AiProjectsSelect<true>;
    'prompt-templates': PromptTemplatesSelect<false> | PromptTemplatesSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'blog-templates': BlogTemplatesSelect<false> | BlogTemplatesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'site-links': SiteLinksSelect<false> | SiteLinksSelect<true>;
    'test-runs': TestRunsSelect<false> | TestRunsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-projects".
 */
export interface AiProject {
  id: number;
  name: string;
  status: 'planning' | 'testing' | 'ready' | 'paused';
  /**
   * Person or team responsible for validating this workspace.
   */
  owner?: string | null;
  /**
   * What the tester should be able to prove with this AI workspace.
   */
  goal: string;
  /**
   * Suggested folder under AI_DOCS_DIR, for example Manuals/B2B.
   */
  docsFolder?: string | null;
  defaultModel?: ('grok-4.3' | 'grok-4' | 'grok-3') | null;
  successCriteria?:
    | {
        criterion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes for the tester or editor.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates".
 */
export interface PromptTemplate {
  id: number;
  title: string;
  isEnabled?: boolean | null;
  mode: 'qa' | 'summary' | 'audit' | 'draft';
  /**
   * Stable model behavior: role, language policy, source policy, and safety rules.
   */
  systemPrompt: string;
  /**
   * Reusable prompt text. Testers can copy it into the Workbench question editor.
   */
  userPrompt: string;
  maxChunks?: number | null;
  temperature?: number | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * Stable site key used by editors and link templates.
   */
  slug: string;
  status: 'draft' | 'live' | 'paused' | 'archived';
  /**
   * Canonical domain, for example example.com or blog.example.com.
   */
  primaryDomain: string;
  locale?: ('en' | 'uk' | 'ru' | 'ro' | 'pl' | 'other') | null;
  siteRole?: ('corporate' | 'content-hub' | 'store' | 'support' | 'regional') | null;
  /**
   * Base path for generated blog URLs.
   */
  defaultBlogPath?: string | null;
  owner?: string | null;
  /**
   * Editorial notes, launch dependencies, or routing constraints.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-templates".
 */
export interface BlogTemplate {
  id: number;
  title: string;
  /**
   * Reusable template key, for example buyer-guide or release-note.
   */
  key: string;
  status: 'draft' | 'active' | 'archived';
  templateType: 'guide' | 'news' | 'case-study' | 'comparison' | 'release-note' | 'seo-cluster';
  /**
   * What this template helps the editor produce.
   */
  editorialGoal: string;
  /**
   * Suggested title formula, for example "How to choose {product}".
   */
  titlePattern?: string | null;
  /**
   * Reusable summary guidance for cards and search previews.
   */
  summaryPattern?: string | null;
  structure?:
    | {
        sectionTitle: string;
        sectionRole?: ('intro' | 'body' | 'proof' | 'cta' | 'faq' | 'related-links') | null;
        instructions?: string | null;
        isRequired?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Minimum number of same-site links expected in the post.
   */
  requiredInternalLinks?: number | null;
  /**
   * Minimum number of approved links to other managed sites.
   */
  requiredCrossSiteLinks?: number | null;
  /**
   * Rules for natural anchors, product names, and avoided phrasing.
   */
  anchorTextGuidance?: string | null;
  /**
   * How this template should connect posts, articles, and site hubs.
   */
  relatedContentStrategy?: string | null;
  aiPrompts?: {
    /**
     * Prompt used to turn business requirements into a blog brief.
     */
    briefPrompt?: string | null;
    /**
     * Prompt used to draft the article outline.
     */
    outlinePrompt?: string | null;
    /**
     * Prompt used to suggest internal and cross-site links.
     */
    linkingPrompt?: string | null;
  };
  seo?: {
    metaTitlePattern?: string | null;
    metaDescriptionPattern?: string | null;
    keywordGuidance?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Post URL segment under the selected site blog path.
   */
  slug: string;
  status: 'idea' | 'draft' | 'review' | 'scheduled' | 'published';
  /**
   * Frontend link. It works after status is Published.
   */
  publicUrl?: string | null;
  site: number | Site;
  template?: (number | null) | BlogTemplate;
  publishedAt?: string | null;
  /**
   * Short intro for cards, indexes, and AI source previews.
   */
  summary?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Main blog body with inline tools and a reusable cross-site CTA block.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('buying-guide' | 'product-education' | 'news' | 'case-study' | 'knowledge-base') | null;
  audience?: ('customer' | 'partner' | 'internal-editor' | 'support') | null;
  /**
   * Business owner or editor responsible for the post.
   */
  owner?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional canonical URL when the article is syndicated.
   */
  canonicalURL?: string | null;
  relatedArticles?: (number | Article)[] | null;
  relatedPosts?: (number | BlogPost)[] | null;
  /**
   * Approved or proposed links this post should use.
   */
  linkPlan?: (number | SiteLink)[] | null;
  aiAssist?: {
    /**
     * Business brief for AI-assisted drafting.
     */
    brief?: string | null;
    targetKeywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    questionsToAnswer?:
      | {
          question?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * AI or editor notes for where links should appear in the post.
     */
    linkingNotes?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short accessible description for images or RAG documents.
   */
  alt?: string | null;
  /**
   * Optional editor note. For RAG uploads, describe the document purpose.
   */
  caption?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Prototype fallback for small images on Render free. Use object storage for production.
   */
  embeddedImageDataURL?: string | null;
  /**
   * Shows whether an image copy was stored in Postgres for free-plan persistence.
   */
  embeddedImageStatus?: ('stored-in-db' | 'not-image' | 'too-large' | 'no-buffer') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Human-readable URL segment, for example: product-visibility-guide.
   */
  slug: string;
  status: 'draft' | 'review' | 'published';
  /**
   * Frontend link. It works after status is Published.
   */
  publicUrl?: string | null;
  publishedAt?: string | null;
  /**
   * Short intro shown in cards, search results, and previews.
   */
  summary?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Lexical editor: headings, lists, links, uploads, tables, inline toolbar, and structured blocks.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('product-content' | 'internal-guide' | 'release-note' | 'knowledge-base') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Business owner or department responsible for this article.
   */
  owner?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-links".
 */
export interface SiteLink {
  id: number;
  title: string;
  status: 'proposed' | 'approved' | 'live' | 'needs-review' | 'archived';
  linkType: 'contextual' | 'navigation' | 'cta' | 'redirect' | 'language-switch' | 'campaign-transition';
  sourceSite: number | Site;
  targetSite: number | Site;
  /**
   * Source URL path if the link is not tied to a CMS document.
   */
  sourcePath?: string | null;
  /**
   * Optional CMS document where the link should appear.
   */
  sourceContent?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null);
  /**
   * Final destination URL. Use a full URL for external sites.
   */
  targetURL?: string | null;
  /**
   * Optional CMS document that the link should resolve to.
   */
  targetContent?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null);
  /**
   * Visible link text or CTA label.
   */
  anchorText: string;
  placement?: ('body' | 'header' | 'footer' | 'related' | 'blog-card' | 'transition-page') | null;
  /**
   * Lower numbers should be shown first in generated menus.
   */
  priority?: number | null;
  editorNotes?: string | null;
  transitionTemplate?: {
    mode?: ('direct' | 'soft-handoff' | 'campaign-bridge' | 'language-selector' | 'product-bridge') | null;
    headline?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    /**
     * Keep campaign and tracking parameters during transition.
     */
    preserveQueryParams?: boolean | null;
  };
  aiReview?: {
    /**
     * AI/editor reason this link is useful.
     */
    rationale?: string | null;
    risk?: ('low' | 'medium' | 'high') | null;
    suggestedBy?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-runs".
 */
export interface TestRun {
  id: number;
  title: string;
  project?: (number | null) | AiProject;
  promptTemplate?: (number | null) | PromptTemplate;
  status: 'new' | 'passed' | 'needs-review' | 'failed';
  rating?: ('good' | 'okay' | 'bad') | null;
  ranAt?: string | null;
  question: string;
  /**
   * Paste the model answer here when saving a manual validation run.
   */
  answer?: string | null;
  sources?:
    | {
        fileName: string;
        path?: string | null;
        score?: number | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'ai-projects';
        value: number | AiProject;
      } | null)
    | ({
        relationTo: 'prompt-templates';
        value: number | PromptTemplate;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'blog-templates';
        value: number | BlogTemplate;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'site-links';
        value: number | SiteLink;
      } | null)
    | ({
        relationTo: 'test-runs';
        value: number | TestRun;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-projects_select".
 */
export interface AiProjectsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  owner?: T;
  goal?: T;
  docsFolder?: T;
  defaultModel?: T;
  successCriteria?:
    | T
    | {
        criterion?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates_select".
 */
export interface PromptTemplatesSelect<T extends boolean = true> {
  title?: T;
  isEnabled?: T;
  mode?: T;
  systemPrompt?: T;
  userPrompt?: T;
  maxChunks?: T;
  temperature?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  primaryDomain?: T;
  locale?: T;
  siteRole?: T;
  defaultBlogPath?: T;
  owner?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-templates_select".
 */
export interface BlogTemplatesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  status?: T;
  templateType?: T;
  editorialGoal?: T;
  titlePattern?: T;
  summaryPattern?: T;
  structure?:
    | T
    | {
        sectionTitle?: T;
        sectionRole?: T;
        instructions?: T;
        isRequired?: T;
        id?: T;
      };
  requiredInternalLinks?: T;
  requiredCrossSiteLinks?: T;
  anchorTextGuidance?: T;
  relatedContentStrategy?: T;
  aiPrompts?:
    | T
    | {
        briefPrompt?: T;
        outlinePrompt?: T;
        linkingPrompt?: T;
      };
  seo?:
    | T
    | {
        metaTitlePattern?: T;
        metaDescriptionPattern?: T;
        keywordGuidance?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publicUrl?: T;
  site?: T;
  template?: T;
  publishedAt?: T;
  summary?: T;
  coverImage?: T;
  content?: T;
  category?: T;
  audience?: T;
  owner?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  canonicalURL?: T;
  relatedArticles?: T;
  relatedPosts?: T;
  linkPlan?: T;
  aiAssist?:
    | T
    | {
        brief?: T;
        targetKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        questionsToAnswer?:
          | T
          | {
              question?: T;
              id?: T;
            };
        linkingNotes?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-links_select".
 */
export interface SiteLinksSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  linkType?: T;
  sourceSite?: T;
  targetSite?: T;
  sourcePath?: T;
  sourceContent?: T;
  targetURL?: T;
  targetContent?: T;
  anchorText?: T;
  placement?: T;
  priority?: T;
  editorNotes?: T;
  transitionTemplate?:
    | T
    | {
        mode?: T;
        headline?: T;
        description?: T;
        ctaLabel?: T;
        preserveQueryParams?: T;
      };
  aiReview?:
    | T
    | {
        rationale?: T;
        risk?: T;
        suggestedBy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-runs_select".
 */
export interface TestRunsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  promptTemplate?: T;
  status?: T;
  rating?: T;
  ranAt?: T;
  question?: T;
  answer?: T;
  sources?:
    | T
    | {
        fileName?: T;
        path?: T;
        score?: T;
        id?: T;
      };
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publicUrl?: T;
  publishedAt?: T;
  summary?: T;
  coverImage?: T;
  content?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  owner?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  embeddedImageDataURL?: T;
  embeddedImageStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}